#!/usr/bin/env python3
"""Is the tree ready for the rename sweep? A readiness meter now, a gate on the day.

Run it any time to see how far the sweep has drifted from what was rehearsed, and run it as
step 1 of the cutover ([the plan](../../docs/work/present)) to decide whether to proceed.

It asserts what the rehearsal of 2026-09-22 established, each check being something that
failed SILENTLY rather than as a build error:

  1. The sweep's reach is near the rehearsed number, so nothing large landed uncovered.
  2. Every line that must keep the old name still carries its `rename-keep` marker, and the
     sweep still leaves it alone. A marker deleted by an unrelated edit is invisible until a
     device cannot find its firmware.
  3. The two-repository OTA still names two repositories, since the sweep pointing both at
     one leaves a device with nowhere to fall back to.

Exit 0 where the tree is ready, 1 where a check fails, 2 where the sweep itself cannot run.

Throwaway, like everything in this folder: it goes when the rename does.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SWEEP = ROOT / "moondeck" / "repo_rename" / "rename_to_moonlight.py"
# Committed beside the scripts, so the drift between two runs is a diff rather than a memory.
REPORT = ROOT / "moondeck" / "repo_rename" / "check_rename_ready.md"

# What the rehearsal measured, and how far the count may drift before it is worth a look.
# The band is wide on purpose: prose grows, and a hundred more hits in documentation says
# nothing. A jump past it says something landed that the markers may not cover.
REHEARSED_HITS = 1376
DRIFT_ALLOWED = 400

# Lines that must survive the sweep, as (file, the text that must still be there).
# Each is a silent failure: @xref the plan's rehearsal section for what each one breaks.
PROTECTED = [
    ("src/core/system/FirmwareUpdateModule.h", 'kFallbackRepo = "MoonModules/projectMM"'),
    ("src/core/util/FirmwareImage.h", "projectMM-moonbase"),
    ("src/platform/esp32/platform_esp32_ota.cpp", "projectMM-moonbase"),
    ("moonbase/CMakeLists.txt", "projectMM-moonbase"),
    ("docs/reference/MIGRATING.md", "The last release under the projectMM name"),
]


def run_sweep_dry() -> tuple[int, str]:
    """The sweep's own dry run: its hit count, and everything it would touch."""
    r = subprocess.run([sys.executable, str(SWEEP)], capture_output=True, text=True, cwd=ROOT)
    # A dry run exits 1 when it found hits, which is the normal case and not a failure: the
    # count below is what this reads. Only a missing count means the sweep could not run.
    m = re.search(r"\[DRY-RUN\] (\d+) hit\(s\)", r.stdout)
    if not m:
        print(f"check_rename_ready: the sweep reported no count\n{r.stderr}", file=sys.stderr)
        sys.exit(2)
    return int(m.group(1)), r.stdout


def per_area(report: str) -> list[tuple[str, int]]:
    """Where the sweep's hits sit, by directory, so growth has a location rather than a number."""
    areas: dict[str, int] = {}
    # Non-greedy to the count rather than \S+, since a tracked path may contain a space
    # (docs/assets carries several) and stopping at the first one drops the file from its area.
    for m in re.finditer(r"^  (.+?): (\d+) hit", report, re.M):
        area = str(Path(m.group(1)).parent)
        areas[area] = areas.get(area, 0) + int(m.group(2))
    return sorted(areas.items(), key=lambda kv: -kv[1])


def write_report(hits: int, drift: int, failures: list[str], report: str) -> None:
    """The run, as a file git can diff: a count that moved shows WHICH area moved it."""
    out = [
        "# Rename readiness",
        "",
        f"Generated by [`moondeck/repo_rename/check_rename_ready.py`]"
        f"(check_rename_ready.py) on every run. **Do not edit by hand.**",
        "",
        "What the sweep would rewrite today, and whether every line that must keep the old name "
        "still survives it.",
        "",
        "Committed so a change between two runs is a diff. A count that moves says which area "
        "moved it, and a line that loses its protection says so before the switch.",
        "",
        f"**{hits} lines** across the tree, **{drift:+d}** against the rehearsed {REHEARSED_HITS}.",
        "",
        "## Protected lines",
        "",
        "| State | File |",
        "|---|---|",
    ]
    for rel, needle in PROTECTED:
        state = "AT RISK" if any(rel in f for f in failures) else "kept"
        out.append(f"| {state} | `{rel}` |")
    out += ["", "## Where the sweep reaches", "", "| Hits | Area |", "|---:|---|"]
    for area, n in per_area(report)[:20]:
        out.append(f"| {n} | `{area}` |")
    if failures:
        out += ["", "## Not ready", ""] + [f"- {f}" for f in failures]
    else:
        out += ["", "Every check passes: the tree is ready for the sweep.", ""]
    REPORT.write_text("\n".join(out) + "\n")


def main() -> int:
    hits, report = run_sweep_dry()
    failures: list[str] = []

    drift = hits - REHEARSED_HITS
    if abs(drift) > DRIFT_ALLOWED:
        failures.append(
            f"the sweep reaches {hits} lines, {drift:+d} against the rehearsed {REHEARSED_HITS}. "
            f"Re-rehearse before the switch: read the new hits for anything the markers miss."
        )

    # The protected lines: present in the file, and absent from what the sweep would rewrite.
    for rel, needle in PROTECTED:
        path = ROOT / rel
        if not path.is_file():
            failures.append(f"{rel} is gone, so its protected line cannot be checked")
            continue
        if needle not in path.read_text(encoding="utf-8", errors="replace"):
            failures.append(f"{rel} no longer contains: {needle}")
            continue
        if needle in report:
            failures.append(f"{rel} would be swept despite its marker: {needle}")

    # The OTA needs two DIFFERENT repositories, which is the whole point of the fallback.
    fw = (ROOT / "src/core/system/FirmwareUpdateModule.h").read_text(encoding="utf-8")
    repos = re.findall(r'k(?:Release|Fallback)Repo = "([^"]+)"', fw)
    if len(repos) != 2:
        failures.append(f"expected two OTA repositories, found {len(repos)}: {repos}")
    elif repos[0] == repos[1]:
        failures.append(f"both OTA repositories name {repos[0]}, so the fallback is dead")

    print(f"Rename readiness: {hits} lines the sweep would rewrite "
          f"({drift:+d} against the rehearsed {REHEARSED_HITS}).")
    for rel, needle in PROTECTED:
        mark = "kept" if not any(rel in f for f in failures) else "AT RISK"
        print(f"  {mark:>7}  {rel}")
    if len(repos) == 2 and repos[0] != repos[1]:
        print(f"  {'kept':>7}  the OTA names {repos[0]} then {repos[1]}")

    write_report(hits, drift, failures, report)

    if failures:
        print("\nNot ready:")
        for f in failures:
            print(f"  - {f}")
        print(f"\nWritten to {REPORT.relative_to(ROOT)}")
        return 1
    print("\nReady: the sweep's reach is as rehearsed and every protected line survives it.")
    print(f"Written to {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
